---
title: "Homework 3"
author: "Carolyn Hanrahan"
date: "2023-02-01" 
output: html_document
---

This is the Rmarkdown/html file I will use for homework 3 


# Homework 3: Regex/Regular Expressions

## Question 1:
```
find: \s{2,}
replace: ,
``` 
For question one I found 2 or more spaces and replaced those spaces with a comma in order to get the answer. 

## Question 2: 

```
find: (\w+),\s(\w+),\s(.*)
replace: \2 \1 \(\3\)
```
For question 2 I found the first set of one or more characters, followed by a comma and space, followed by the second set of one or more characters, followed by a comma, a space, and "all the rest". I then rearranged these segments so that it goes second set of characters, followed by first, followed by all the rest.  

## Question 3: 

```
find: (.mp3)
replace: \1\n
```
For question 3 I found the literal characters ".mp3" and replaced that with the same thing (/1) and /n to indicate a line break. 

## Question 4: 

```
find: (\d{4})(.*)(.\w{2}\d)
replace: \2\_\3
```
For question 4 I found the first four digits, and then "all of the rest" up until a period followed by 2 characters and a digit. I then rearranged these parentheses to get the correct order. 

## Question 5: 

```
find: (\w)(\w+),(\w+),(\d+.\d+),(\d+)
replace: \1_\3_\5
```
For question 5 I began by isolating the first word character in a parentheses, followed by the rest of the word, a comma, the second word, and the string of numbers. I then rearranged the ordering of these parentheses segments to create the final product. 

## Question 6

```
find: (\w_)(\w{4})(.*,)(\d+)
replace: \1 \2,\4
```
For question 6, I found the first character followed by an underscore, followed by the second set of 4 characters, "all the rest" until the comma, and the string of numbers. I then rearranged as seen above. 

## Question 7

```
find: (\w{3})(\w+),(\w{3})(\w{3})(\w+),(\d+.)(\d)(\d+)
replace: \1\3\, \7 \5 \6
```
Finally for question 7 I found the first set of three characters, followed by the rest of the word, a comma, the next set of three characters, the next set of three characters, the rest of the word, a comma, and the number segments. I then rearranged these parenthese into the appropriate order. Thank you for your help!



